### PR TITLE
Add contributing

### PR DESCRIPTION
**Pull request by ylorenzana**
I added a CONTRIBUTING.md file.

### CODE REVIEW

**Comment by jaydp17** [comment]
Hey, @ylorenzana thanks for the PR ☺️

This looks great!
All it needs is a section with instructions on how to set up the project.
Have a look at https://github.com/jaydp17/youtube-playlist-sorter/issues/4#issuecomment-340214016 for a rough set of instructions

**Comment by jaydp17** [comment]
@ylorenzana  I'm sorry for not being clear but I was talking about setting up the project for development.

The guidelines given in the readme are for usage (people who are consuming the package) not fo development.

**Comment by ylorenzana** [comment]
@jaydp17 Apologies for the delayed response — I will work on this shortly.

**Comment by ylorenzana** [comment]
I changed the wording in the CONTRIBUTING.md file, I kept the link to the README.md, the file best suited for instructions on how to setup the project for development in my opinion; I will update the README.md file to reflect these changes and open a new PR.

**Comment by ylorenzana** [comment]
I decided not to open a new pull request and just commited the changes to the same branch. I added instructions for setup to the README.md file, I think it makes more sense this way. Let me know what you think.

**Comment by jaydp17** [comment]
sorry for the delay in response.

Merging it now 🎉

**Pull request merged**
