### PR TITLE
added node version warning

### PR DESCRIPTION
**Pull request by ghost**
Used https://github.com/typicode/please-upgrade-node to check for node version warning.

### CODE REVIEW

**Comment by jaydp17** [comment]
Hey @monera23
Thanks for the PR, but this doesn't seem to be working.

So the basic idea is whenever the user is using node.js version < 4, the CLI shouldn't crash on him, instead, it should show up a nice message saying it please upgrade node.

I tried using node 0.12, it's crashing 😕
Can you please check what's going wrong?

**Comment by ghost** [comment]
The module https://github.com/typicode/please-upgrade-node ends the process with a warning. So instead of commenting out the `` process.exit(1) `` line in the (please-upgrade-node)module, I was thinking of writing a new file with the same logic? What do you say?

**Comment by jaydp17** [comment]
@monera23 I didn't understand why are you trying to comment out `process.exit(1)`?
We do want the program to exit if node version is < 4.0

**Comment by ghost** [comment]
I have updated it. The program exits with the warning message.

**Comment by jaydp17** [comment]
@monera23 why not use https://github.com/typicode/please-upgrade-node directly?

**Comment by ghost** [comment]
When I tried using it the cli always crashes with error message status 1. Instead if I just used process.exit(0). I ends the cli with the warning message.

**Comment by jaydp17** [comment]
when I tried it, it was crashing because of the unsupported syntax. is it the case with you?
We need to print the warning message and exit with status 1

**Comment by ghost** [comment]
For me it gives this error
`` npm ERR!  code ELIFECYCLE
npm ERR! errno 1 ``

**Comment by jaydp17** [comment]
can you provide the entire error message block?
starting from where you wrote the command to the end

**Comment by ghost** [comment]
```
npm run dev 'https://www.youtube.com/playlist\?list=PLp_A7BZlpSOcPP7p9sREbjab4ETq9-tN3'

> youtube-playlist-sorter@0.2.2 dev /Users/shrikantjituri/Documents/someWork/youtube-playlist-sorter
> babel-node src/index.js "https://www.youtube.com/playlist\?list=PLp_A7BZlpSOcPP7p9sREbjab4ETq9-tN3"

youtube-playlist-sorter requires at least version 9.0.0 of Node, Please Upgrade

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-playlist-sorter@0.2.2 dev: `babel-node src/index.js "https://www.youtube.com/playlist\?list=PLp_A7BZlpSOcPP7p9sREbjab4ETq9-tN3"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-playlist-sorter@0.2.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jaydp17** [comment]
that's npm showing you error.
So for a workaround, try
```sh
$ ./node_modules/.bin/babel-node src/index.js
```

**Comment by ghost** [comment]
So should I use this https://github.com/typicode/please-upgrade-node? And any other change so that it doesn't the above error ?

**Comment by jaydp17** [comment]
yes please try to use https://github.com/typicode/please-upgrade-node.

The way you can test it is
```sh
# use node > 8
$ node -v
# 8.7.0

# build the project
$ npm run build

# switch to node 0.12
$ nvm use 0.12

# run the project
$ node ./lib/index.js
# this should give the error and exit
```

**Pull request closed without merging**
